userpark/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from userpark.views import UserCreateView, CustomerSignUpView, StaffSignUpView, UserLoginView, UserProfileView, UserUpdatePropicView, UserUpdateFirstNameView, UserUpdateLastNameView, UserUpdateGenderView, UserUpdateEmailView, UserUpdateBirthDateView, UserUpdatePasswordView, UserDeleteProfileView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'userpark'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('user_create/', UserCreateView.as_view(), name='user-create'),
    path('user_create/customer_sign_in/', CustomerSignUpView.as_view(), name='customer-create'),
    path('user_create/staff_sign_in/', StaffSignUpView.as_view(), name='staff-create'),
    path('user_profile/', UserProfileView.as_view(), name='user-profile'),
    path('user_profile/<slug:slug>/update_propic/', UserUpdatePropicView.as_view(), name='user-profile-update-propic'),   # HERE
    path('user_profile/<slug:slug>/update_first_name/', UserUpdateFirstNameView.as_view(), name='user-profile-update-firstname'),
    path('user_profile/<slug:slug>/update_last_name/', UserUpdateLastNameView.as_view(), name='user-profile-update-lastname'),
    path('user_profile/<slug:slug>/update_gender/', UserUpdateGenderView.as_view(), name='user-profile-update-gender'),
    path('user_profile/<slug:slug>/update_email/', UserUpdateEmailView.as_view(), name='user-profile-update-email'),
    path('user_profile/<slug:slug>/update_birth_date/', UserUpdateBirthDateView.as_view(), name='user-profile-update-birthdate'),
    path('user_profile/<slug:slug>/update_password/', UserUpdatePasswordView.as_view(), name='user-profile-update-password'),
    path('user_profile/<slug:slug>/delete_profile/', UserDeleteProfileView.as_view(), name='user-profile-delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterland/urls.py
from django.contrib import admin
from django.urls import path, include
from waterland.views import HomeView, WaterlandParkView, AboutUsView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('waterpark/', include('waterpark.urls')),
    path('userpark/', include('userpark.urls')),
    path('reviewpark/', include('reviewpark.urls')),
    path('', HomeView.as_view(), name='home'),
    path('waterland_park', WaterlandParkView.as_view(), name='waterland-park-info-showcase'),
    path('about_us', AboutUsView.as_view(), name='waterland-about-us'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterpark/urls.py
from django.urls import path
from waterpark.views import CustomerServiceMenuView, CustomerBuyTiketView, CustomerBuySeasonPassView, CustomerTiketListView, CustomerSeasonPassListView, StaffManageTiketMainView, StaffManageSeasonpassMainView, SearchTiketByDateListView, SearchTiketByYearListView, SearchTiketByRangeListView, SearchSeasonpassByYearListView, SearchCustomerTiketView, SearchCustomerSeasonpassView, SearchCustomerTiketListView, SearchCustomerSeasonpassListView, GetTiketTodayView, GetTiketTodayStaffView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'waterpark'

urlpatterns = [

    path('tickets&seasonpass/', CustomerServiceMenuView.as_view(), name='customerservices'),
    path('tickets&seasonpass/buy_a_ticket/', CustomerBuyTiketView.as_view(), name='customer-buy-tiket'),
    path('tickets&seasonpass/buy_a_seasonpass/', CustomerBuySeasonPassView.as_view(), name='customer-buy-seasonpass'),
    path('tickets&seasonpass/my_tickets/', CustomerTiketListView.as_view(), name='customer-tiket-list'),
    path('tickets&seasonpass/my_seasonpass/', CustomerSeasonPassListView.as_view(), name='customer-seasonpass-list'),
    path('ticket_management/', StaffManageTiketMainView.as_view(), name='staff-manage-tiket-main'),
    path('seasonpass_management/', StaffManageSeasonpassMainView.as_view(), name='staff-manage-seasonpass-main'),
    path('ticket_management/search_by_date/', SearchTiketByDateListView.as_view(), name='staff-manage-tiket-by-day'),
    path('ticket_management/search_by_year/', SearchTiketByYearListView.as_view(), name='staff-manage-tiket-by-year'),
    path('ticket_management/search_by_range/', SearchTiketByRangeListView.as_view(), name='staff-manage-tiket-by-range'),
    path('seasonpass_management/search_by_year/', SearchSeasonpassByYearListView.as_view(), name='staff-manage-seasonpass-by-year'),
    path('customer_search_ticket/', SearchCustomerTiketView.as_view(), name='staff-search-tiket-for-user'),
    path('customer_search_ticket/customer/', SearchCustomerTiketListView.as_view(), name='staff-search-tiket-for-user-results'),
    path('customer_search_seasonpass/', SearchCustomerSeasonpassView.as_view(), name='staff-search-seasonpass-for-user'),
    path('customer_search_seasonpass/customer/', SearchCustomerSeasonpassListView.as_view(), name='staff-search-seasonpass-for-user-results'),
    path('tickets&seasonpass/my_tickets/today', GetTiketTodayView.as_view(), name='customer-tiket-list-today'),
    path('customer_search_ticket/customer/today', GetTiketTodayStaffView.as_view(), name='staff-search-tiket-for-user-results-today'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterpark/models.py
from django.db import models
from django.utils import timezone
from userpark.models import User as myUser
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import date, timedelta
from PIL import Image
from django.template.defaultfilters import slugify
import uuid as UUID_LIB

# Where to upload pics of the user into user directory


def media_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance, filename)

# Other def


def validity_delta():
    start_date = date(date.today().year, 1, 1)
    end_date = date.today()
    delta_diff = end_date - start_date
    return 365 - delta_diff.days

# Create your models here.


class Tiket(models.Model):
    customer = models.ForeignKey(myUser, on_delete=models.SET_NULL, null=True)    # ForeignKey many to one
    tiket_slug = models.SlugField(null=False, unique=True)            # Slug reference used for each tiket created
    date_of_purchase = models.DateTimeField(default=timezone.now, null=False, blank=False)
    validity_day = models.DateField(help_text="Choose the day you will come to Waterland", null=False,
                                    validators=[MinValueValidator(limit_value=date.today), MaxValueValidator(limit_value=date.today()+timedelta(days=365))],
                                    default=date.today, blank=False, verbose_name='Entry Waterland date')
    cost = models.IntegerField(default=15, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Tickets'

    def __str__(self):
        try:
            return f'{self.customer.username} - Ticket:{self.tiket_slug}'
        except:
            return f'DELETED-USER-Ticket:{self.tiket_slug}'

    def save(self, *args, **kwargs):
        if not self.tiket_slug:
            self.tiket_slug = slugify(str(UUID_LIB.uuid1()))
        return super().save(*args, **kwargs)   # Save all at database


class SeasonPass(models.Model):
    customer = models.ForeignKey(myUser, on_delete=models.SET_NULL, null=True)
    seasonpass_slug = models.SlugField(null=False, unique=True)
    date_of_purchase = models.DateTimeField(default=timezone.now, null=False, blank=False)
    validity_from = models.DateField(default=date.today, null=False, blank=False)
    validity_to = models.DateField(default=date.today()+timedelta(days=validity_delta()), null=False, blank=False)
    seasonpass_photo = models.ImageField(upload_to=media_directory_path, blank=False, null=False,
                                         help_text='Add your photo, it shall added to your season pass',
                                         verbose_name='SeasonPass Photo')
    cost = models.IntegerField(default=125, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'SeasonPass'

    def __str__(self):
        try:
            return f'{self.customer.username} - Profile/SeasonPass'
        except:
            return f'DELETED-USER-SeasonPass:{self.seasonpass_slug}'

    def save(self, *args, **kwargs):
        if not self.seasonpass_slug:
            self.seasonpass_slug = slugify(str(UUID_LIB.uuid1()))
        super().save(*args, **kwargs)  # Save all at database

        if self.seasonpass_photo:    # Using Pillow Package to resize the seasonpass photo
            img = Image.open(self.seasonpass_photo.path)
            if img.height > 200 or img.width > 200:
                output_size = (200, 200)
                img.thumbnail(output_size)
                img.save(self.seasonpass_photo.path)

waterpark/forms.py
from django import forms
from waterpark.models import Tiket, SeasonPass
from datetime import date


class TiketForm(forms.ModelForm):
    class Meta:
        model = Tiket
        fields = ['validity_day']
        fields_required = ['validity_day']
        widgets = {
            'validity_day': forms.SelectDateWidget(empty_label=('Year', 'Month', 'Day'), years=range(date.today().year, date.today().year+2)),
        }


class SeasonPassForm(forms.ModelForm):
    class Meta:
        model = SeasonPass
        fields = ['seasonpass_photo']
        fields_required = ['seasonpass_photo']

waterpark/templates/waterpark/staff/manage_seasonpass_menu.html
{% extends 'navbase.html' %}

{% block title %}STAFF: {{ user.username }}, history SeasonPass{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <div class="text-center">
            <h1 style="color:blue;">STAFF SEASONPASS MANAGEMENT</h1>
        </div>

        <div class="container p-3 my-3 border">
            <div class="text-center">
                <h5 style="color: aqua">Searching by year</h5>
                <form action="{% url 'waterpark:staff-manage-seasonpass-by-year' %}" method="get">
                    <label for="yearform">Enter a year:</label>
                    <input type="number" id="yearform" name="yearform" min="2022" max="" placeholder="Year..." required><br><br>
                    <button type="submit" class="btn btn-info">Search</button>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

{% block javascript %}

    <script>

        let yyyy = new Date().getFullYear()
        yyyy += 1
        document.getElementById("yearform").setAttribute("max", yyyy)

    </script>

{% endblock %}

waterpark/templates/waterpark/staff/manage_tiket_menu.html
{% extends 'navbase.html' %}

{% block title %}STAFF: {{ user.username }}, history Ticket{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <div class="text-center">
            <h1 style="color:blue;">STAFF TICKETS MANAGEMENT</h1>
        </div>

        <div class="container p-3 my-3 border">
            <div class="text-center">
                <h5 style="color: aqua">Searching by day</h5>
                <form action="{% url 'waterpark:staff-manage-tiket-by-day' %}" method="get">
                    <label for="dateform">Enter a date:</label>
                    <input type="date" id="dateform" name="dateform" min="2022-01-01" max="" required><br><br>
                    <button type="submit" class="btn btn-info">Search</button>
                </form>
            </div>
        </div>

        <div class="container p-3 my-3 border">
            <div class="text-center">
                <h5 style="color: aqua">Searching by custom range</h5>
                <form action="{% url 'waterpark:staff-manage-tiket-by-range' %}" method="get" onsubmit="validation()">
                    <label for="dateminform">Enter from date:</label>
                    <input type="date" id="dateminform" name="dateminform" min="2022-01-01" max="" required><br><br>
                    <label for="datemaxform">Enter to date:</label>
                    <input type="date" id="datemaxform" name="datemaxform" min="2022-01-01" max="" required><br><br>
                    <button type="submit" class="btn btn-info">Search</button>
                </form>
            </div>
        </div>

        <div class="container p-3 my-3 border">
            <div class="text-center">
                <h5 style="color: aqua">Searching by year</h5>
                <form action="{% url 'waterpark:staff-manage-tiket-by-year' %}" method="get">
                    <label for="yearform">Enter a year:</label>
                    <input type="number" id="yearform" name="yearform" min="2022" max="" placeholder="Year..." required><br><br>
                    <button type="submit" class="btn btn-info">Search</button>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

{% block javascript %}

    <script>
        let today = new Date()
        let dd = today.getDate()
        let mm = today.getMonth() //January is 0!
        let yyyy = today.getFullYear()
        yyyy += 2

        if (dd < 10) {
           dd = '0' + dd
        }

        if (mm < 10) {
           mm = '0' + mm
        }

        today = yyyy + '-' + mm + '-' + dd
        let todaymin = yyyy + '-' + mm + '-' + (dd-1)

        document.getElementById("dateform").setAttribute("max", today)
        document.getElementById("yearform").setAttribute("max", yyyy)
        document.getElementById("dateminform").setAttribute("max", todaymin)
        document.getElementById("datemaxform").setAttribute("max", today)
    </script>

    <script>

            function validation() {
            let v1 = document.getElementById('dateminform')
            let v2 = document.getElementById('datemaxform')
            let d1 = new Date(v1.value)
            let d2 = new Date(v2.value)

           if (d1 < d2) {
               return true
           }else{
               alert("Date is not in valid range")
           }
           }

    </script>

{% endblock %}

waterpark/templates/waterpark/staff/staff_search_seasonpass_list.html
{% extends 'navbase.html' %}

{% block title %}STAFF: {{ user.username }}, manage search SeasonPass{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
    <div class="text-center">
        <h1 style="color:blue;">STAFF SEASONPASS SEARCH RESULTS {% if request.GET.yearform %}<br>(YEAR: {{ request.GET.yearform }}){% endif %}</h1><br>
        <h2><b>* SeasonPass found: {{ seasonpass_list.count }}</b></h2>
        <h2><b>* Unit price: $125</b></h2>
        <h2 id="price" style="color: greenyellow"><b>* Total gain: $</b></h2>
        <br><a href="{% url 'waterpark:staff-manage-seasonpass-main' %}"><button type="button" class="btn btn-info">Back</button></a><br>
    </div><br>

    <div class="container p-3 my-3 border">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="text-center">
                    <h3>SEASONPASS LIST</h3>
                    <p>(Flash View)</p>
                </div>
            </div>
              {% for seasonpass in seasonpass_list %}
                  <div class="carousel-item">
                    <div class="text-center">
                      {% if seasonpass.customer.get_username %}
                        <p><strong style="color: darkorange">Customer (username):</strong>   {{ seasonpass.customer.get_username }}</p>
                      {% else %}
                        <p><strong style="color: darkorange">Customer (username):</strong>   Deleted customer</p>
                      {% endif %}
                      <p><strong style="color: darkorange">Purchase date:</strong>     {{ seasonpass.date_of_purchase }}</p>
                      <p><strong style="color: darkorange">Validity from date:</strong>     {{ seasonpass.validity_from }}</p>
                      <p><strong style="color: darkorange">Validity to date:</strong>     {{ seasonpass.validity_to }}</p>
                    </div>
                  </div>
              {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        {% if seasonpass_list.count == 0 %}
            <div class="text-center">
                <p>No seasonpass found</p>
            </div>
        {% endif %}
    </div>

    </div>
{% endblock %}

{% block javascript %}

    <script>
        const seasonpasslen = {{ seasonpass_list.count }}
        document.getElementById("price").innerHTML += (seasonpasslen*125).toString()
    </script>

{% endblock %}

waterpark/templates/waterpark/staff/staff_search_tiket_list.html
{% extends 'navbase.html' %}
{% load static %}

{% block title %}STAFF: {{ user.username }}, manage search Ticket{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
    <div class="text-center">
        <h1 style="color:blue;">STAFF TICKETS SEARCH RESULTS {% if request.GET.dateform %}<br>(DAY: {{ request.GET.dateform }}){% endif %}{% if request.GET.dateminform and request.GET.datemaxform %}<br>(FROM: {{ request.GET.dateminform }} TO: {{ request.GET.datemaxform }}){% endif %}{% if request.GET.yearform %}<br>(YEAR: {{ request.GET.yearform }}){% endif %}</h1><br>
        <h2><b>* Tickets found: {{ tiket_list.count }}</b></h2>
        <h2><b>* Unit price: $15</b></h2>
        <h2 id="price" style="color: greenyellow"><b>* Total gain: $</b></h2>
        <br><a href="{% url 'waterpark:staff-manage-tiket-main' %}"><button type="button" class="btn btn-info">Back</button></a><br>
    </div><br>

    <!-- graph  -->
    <div class="text-center">
        <canvas id="myChart"></canvas>
    </div>
    <!-- graph  -->

    <div class="container p-3 my-3 border">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="text-center">
                    <h3>TICKETS LIST</h3>
                    <p>(Flash View)</p>
                </div>
            </div>
              {% for tiket in tiket_list %}
                  <div class="carousel-item">
                    <div class="text-center">
                      {% if tiket.customer.get_username %}
                        <p><strong style="color: darkorange">Customer (username):</strong>   {{ tiket.customer.get_username }}</p>
                      {% else %}
                        <p><strong style="color: darkorange">Customer (username):</strong>   Deleted customer</p>
                      {% endif %}
                      <p><strong style="color: darkorange">Purchase date:</strong>     {{ tiket.date_of_purchase }}</p>
                      <p><strong style="color: darkorange">Validity date:</strong>     {{ tiket.validity_day }}</p>
                    </div>
                  </div>
              {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        {% if tiket_list.count == 0 %}
            <div class="text-center">
                <p>No tickets found</p>
            </div>
        {% endif %}
    </div>

    </div>
{% endblock %}

{% block javascript %}

    <script>
        const tiketlen = {{ tiket_list.count }}
        document.getElementById("price").innerHTML += (tiketlen*15).toString()
    </script>

    <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>  -->
    <script src="{% static 'js/chart.js' %}"></script>

    <script>
    const listlabels = [{% for tiket in tiket_list %}'{{ tiket.validity_day }}',{% endfor %}];
    const setlabels = new Set(listlabels);
    let jsonvalue = {};
    for (const key of setlabels) {
    jsonvalue[key] = 0;
    }
    for (const key of listlabels){
        jsonvalue[key] += 1;
    }
    const listvaluecount = [];
    for (const key of setlabels){
        listvaluecount.push(jsonvalue[key]);
    }
    // console.log(listvaluecount)

  const labels = Array.from(setlabels);   // x days

  const data = {
    labels: labels,
    datasets: [{
      label: 'Tickets Quantity',
      backgroundColor: 'rgb(255, 99, 132)',
      borderColor: 'rgb(255, 99, 132)',
      data: listvaluecount,                  // y  quantity tikets
    }]
  };

  const config = {
    type: 'line',
    data: data,
    options: {}
  };
</script>

<script>
  const myChart = new Chart(
    document.getElementById('myChart'),
    config
  );
</script>

{% endblock %}