userpark/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from userpark.views import UserCreateView, CustomerSignUpView, StaffSignUpView, UserLoginView, UserProfileView, UserUpdatePropicView, UserUpdateFirstNameView, UserUpdateLastNameView, UserUpdateGenderView, UserUpdateEmailView, UserUpdateBirthDateView, UserUpdatePasswordView, UserDeleteProfileView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'userpark'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('user_create/', UserCreateView.as_view(), name='user-create'),
    path('user_create/customer_sign_in/', CustomerSignUpView.as_view(), name='customer-create'),
    path('user_create/staff_sign_in/', StaffSignUpView.as_view(), name='staff-create'),
    path('user_profile/', UserProfileView.as_view(), name='user-profile'),
    path('user_profile/<slug:slug>/update_propic/', UserUpdatePropicView.as_view(), name='user-profile-update-propic'),   # HERE
    path('user_profile/<slug:slug>/update_first_name/', UserUpdateFirstNameView.as_view(), name='user-profile-update-firstname'),
    path('user_profile/<slug:slug>/update_last_name/', UserUpdateLastNameView.as_view(), name='user-profile-update-lastname'),
    path('user_profile/<slug:slug>/update_gender/', UserUpdateGenderView.as_view(), name='user-profile-update-gender'),
    path('user_profile/<slug:slug>/update_email/', UserUpdateEmailView.as_view(), name='user-profile-update-email'),
    path('user_profile/<slug:slug>/update_birth_date/', UserUpdateBirthDateView.as_view(), name='user-profile-update-birthdate'),
    path('user_profile/<slug:slug>/update_password/', UserUpdatePasswordView.as_view(), name='user-profile-update-password'),
    path('user_profile/<slug:slug>/delete_profile/', UserDeleteProfileView.as_view(), name='user-profile-delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterland/urls.py
from django.contrib import admin
from django.urls import path, include
from waterland.views import HomeView, WaterlandParkView, AboutUsView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('waterpark/', include('waterpark.urls')),
    path('userpark/', include('userpark.urls')),
    path('reviewpark/', include('reviewpark.urls')),
    path('', HomeView.as_view(), name='home'),
    path('waterland_park', WaterlandParkView.as_view(), name='waterland-park-info-showcase'),
    path('about_us', AboutUsView.as_view(), name='waterland-about-us'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterpark/urls.py
from django.urls import path
from waterpark.views import CustomerServiceMenuView, CustomerBuyTiketView, CustomerBuySeasonPassView, CustomerTiketListView, CustomerSeasonPassListView, StaffManageTiketMainView, StaffManageSeasonpassMainView, SearchTiketByDateListView, SearchTiketByYearListView, SearchTiketByRangeListView, SearchSeasonpassByYearListView, SearchCustomerTiketView, SearchCustomerSeasonpassView, SearchCustomerTiketListView, SearchCustomerSeasonpassListView, GetTiketTodayView, GetTiketTodayStaffView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'waterpark'

urlpatterns = [

    path('tickets&seasonpass/', CustomerServiceMenuView.as_view(), name='customerservices'),
    path('tickets&seasonpass/buy_a_ticket/', CustomerBuyTiketView.as_view(), name='customer-buy-tiket'),
    path('tickets&seasonpass/buy_a_seasonpass/', CustomerBuySeasonPassView.as_view(), name='customer-buy-seasonpass'),
    path('tickets&seasonpass/my_tickets/', CustomerTiketListView.as_view(), name='customer-tiket-list'),
    path('tickets&seasonpass/my_seasonpass/', CustomerSeasonPassListView.as_view(), name='customer-seasonpass-list'),
    path('ticket_management/', StaffManageTiketMainView.as_view(), name='staff-manage-tiket-main'),
    path('seasonpass_management/', StaffManageSeasonpassMainView.as_view(), name='staff-manage-seasonpass-main'),
    path('ticket_management/search_by_date/', SearchTiketByDateListView.as_view(), name='staff-manage-tiket-by-day'),
    path('ticket_management/search_by_year/', SearchTiketByYearListView.as_view(), name='staff-manage-tiket-by-year'),
    path('ticket_management/search_by_range/', SearchTiketByRangeListView.as_view(), name='staff-manage-tiket-by-range'),
    path('seasonpass_management/search_by_year/', SearchSeasonpassByYearListView.as_view(), name='staff-manage-seasonpass-by-year'),
    path('customer_search_ticket/', SearchCustomerTiketView.as_view(), name='staff-search-tiket-for-user'),
    path('customer_search_ticket/customer/', SearchCustomerTiketListView.as_view(), name='staff-search-tiket-for-user-results'),
    path('customer_search_seasonpass/', SearchCustomerSeasonpassView.as_view(), name='staff-search-seasonpass-for-user'),
    path('customer_search_seasonpass/customer/', SearchCustomerSeasonpassListView.as_view(), name='staff-search-seasonpass-for-user-results'),
    path('tickets&seasonpass/my_tickets/today', GetTiketTodayView.as_view(), name='customer-tiket-list-today'),
    path('customer_search_ticket/customer/today', GetTiketTodayStaffView.as_view(), name='staff-search-tiket-for-user-results-today'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterpark/models.py
from django.db import models
from django.utils import timezone
from userpark.models import User as myUser
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import date, timedelta
from PIL import Image
from django.template.defaultfilters import slugify
import uuid as UUID_LIB

# Where to upload pics of the user into user directory


def media_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance, filename)

# Other def


def validity_delta():
    start_date = date(date.today().year, 1, 1)
    end_date = date.today()
    delta_diff = end_date - start_date
    return 365 - delta_diff.days

# Create your models here.


class Tiket(models.Model):
    customer = models.ForeignKey(myUser, on_delete=models.SET_NULL, null=True)    # ForeignKey many to one
    tiket_slug = models.SlugField(null=False, unique=True)            # Slug reference used for each tiket created
    date_of_purchase = models.DateTimeField(default=timezone.now, null=False, blank=False)
    validity_day = models.DateField(help_text="Choose the day you will come to Waterland", null=False,
                                    validators=[MinValueValidator(limit_value=date.today), MaxValueValidator(limit_value=date.today()+timedelta(days=365))],
                                    default=date.today, blank=False, verbose_name='Entry Waterland date')
    cost = models.IntegerField(default=15, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Tickets'

    def __str__(self):
        try:
            return f'{self.customer.username} - Ticket:{self.tiket_slug}'
        except:
            return f'DELETED-USER-Ticket:{self.tiket_slug}'

    def save(self, *args, **kwargs):
        if not self.tiket_slug:
            self.tiket_slug = slugify(str(UUID_LIB.uuid1()))
        return super().save(*args, **kwargs)   # Save all at database


class SeasonPass(models.Model):
    customer = models.ForeignKey(myUser, on_delete=models.SET_NULL, null=True)
    seasonpass_slug = models.SlugField(null=False, unique=True)
    date_of_purchase = models.DateTimeField(default=timezone.now, null=False, blank=False)
    validity_from = models.DateField(default=date.today, null=False, blank=False)
    validity_to = models.DateField(default=date.today()+timedelta(days=validity_delta()), null=False, blank=False)
    seasonpass_photo = models.ImageField(upload_to=media_directory_path, blank=False, null=False,
                                         help_text='Add your photo, it shall added to your season pass',
                                         verbose_name='SeasonPass Photo')
    cost = models.IntegerField(default=125, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'SeasonPass'

    def __str__(self):
        try:
            return f'{self.customer.username} - Profile/SeasonPass'
        except:
            return f'DELETED-USER-SeasonPass:{self.seasonpass_slug}'

    def save(self, *args, **kwargs):
        if not self.seasonpass_slug:
            self.seasonpass_slug = slugify(str(UUID_LIB.uuid1()))
        super().save(*args, **kwargs)  # Save all at database

        if self.seasonpass_photo:    # Using Pillow Package to resize the seasonpass photo
            img = Image.open(self.seasonpass_photo.path)
            if img.height > 200 or img.width > 200:
                output_size = (200, 200)
                img.thumbnail(output_size)
                img.save(self.seasonpass_photo.path)

waterpark/forms.py
from django import forms
from waterpark.models import Tiket, SeasonPass
from datetime import date


class TiketForm(forms.ModelForm):
    class Meta:
        model = Tiket
        fields = ['validity_day']
        fields_required = ['validity_day']
        widgets = {
            'validity_day': forms.SelectDateWidget(empty_label=('Year', 'Month', 'Day'), years=range(date.today().year, date.today().year+2)),
        }


class SeasonPassForm(forms.ModelForm):
    class Meta:
        model = SeasonPass
        fields = ['seasonpass_photo']
        fields_required = ['seasonpass_photo']

waterpark/templates/waterpark/staff/detail/staff_dseasonpass_form.html
{% extends 'navbase.html' %}

{% block title %}STAFF: customer seasonpass search{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <div class="text-center">
            <h1 style="color:blue;">LIST CUSTOMER SEASONPASS SEARCH</h1>
        </div>

        <div class="container p-3 my-3 border">
            <div class="text-center">
                <h5 style="color: aqua">Searching by username</h5>
                <form action="{% url 'waterpark:staff-search-seasonpass-for-user-results' %}" method="get">
                    <label for="nameform">Enter a username:</label>
                    <input type="text" id="nameform" name="nameform" placeholder="Username here..." required><br><br>
                    <button type="submit" class="btn btn-info">Search</button>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

waterpark/templates/waterpark/staff/detail/staff_dtiket_form.html
{% extends 'navbase.html' %}

{% block title %}STAFF: customer ticket search{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <div class="text-center">
            <h1 style="color:blue;">LIST CUSTOMER TICKET SEARCH</h1>
        </div>

        <div class="container p-3 my-3 border">
            <div class="text-center">
                <h5 style="color: aqua">Searching by username</h5>
                <form action="{% url 'waterpark:staff-search-tiket-for-user-results' %}" method="get">
                    <label for="nameform">Enter a username:</label>
                    <input type="text" id="nameform" name="nameform" placeholder="Username here..." required><br><br>
                    <button type="submit" class="btn btn-info">Search</button>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

waterpark/templates/waterpark/staff/detail/staff_seasonpass_detail.html
{% extends 'navbase.html' %}

{% block title %}STAFF: SeasonPass results{% endblock %}

{% block bodybase %}

    <div class="text-center" style="background-color: lightgray">
        <h1><strong><u>SEASON PASS RESULTS:</u></strong></h1><br>
        <a href="{% url 'waterpark:staff-search-seasonpass-for-user' %}"><button type="button" class="btn btn-info">Back</button></a>
        {% if request.GET.nameform %}
           <br><br>
           <p><strong><u>Searching for "{{ request.GET.nameform }}" season pass</u></strong></p><br>
        {% endif %}
        </div>
    <div class="container p-3 my-3 bg-dark text-white">
    {% for seasonpass in seasonpass_list %}
        <br>
        <div class="container p-3 my-3 border">
        <table class="table table-striped table-dark">
          <thead>
            <tr>
                <th scope="col"><strong>SEASON PASS FIELDS</strong></th>
              <th scope="col"><strong>INFO</strong></th>
            </tr>
          </thead>
        <tbody>
            <tr>
            <th scope="row">CUSTOMER USERNAME:</th>
             <td>{{ seasonpass.customer.get_username }}</td>
            </tr>
            <tr>
            <th scope="row">CUSTOMER BIRTHDAY:</th>
             <td>{{ seasonpass.customer.birth_date }}</td>
            </tr>
            <tr>
            <th scope="row">CUSTOMER GENDER:</th>
             <td>{{ seasonpass.customer.gender }}</td>
            </tr>
            <tr>
            <th scope="row">CUSTOMER EMAIL:</th>
             <td>{{ seasonpass.customer.email }}</td>
            </tr>
            {% if seasonpass.customer.first_name %}
                <tr>
                <th scope="row">CUSTOMER FIRST NAME:</th>
                <td>{{ seasonpass.customer.first_name }}</td>
                </tr>
            {% endif %}
            {% if seasonpass.customer.last_name %}
                <tr>
                <th scope="row">CUSTOMER LAST NAME:</th>
                <td>{{ seasonpass.customer.last_name }}</td>
                </tr>
            {% endif %}
            <tr>
            <th scope="row">SEASON PASS PHOTO:</th>
             <td><img src="/media/{{ MEDIA_URL }}{{ seasonpass.seasonpass_photo }}" alt="propic" class="img-thumbnail"></td>
            </tr>
            <tr>
            <th scope="row">SEASON PASS ID:</th>
             <td>{{ seasonpass.seasonpass_slug }}</td>
            </tr>
            <tr>
            <th scope="row">DATE OF PURCHASE:</th>
             <td>{{ seasonpass.date_of_purchase }}</td>
            </tr>
            <tr>
            <th scope="row">PRICE:</th>
             <td>${{ seasonpass.cost }}</td>
            </tr>
            <tr>
            <th scope="row">VALIDITY FROM:</th>
             <td>{{ seasonpass.validity_from }}</td>
            </tr>
            <tr>
            <th scope="row">VALIDITY TO:</th>
             <td>{{ seasonpass.validity_to }}</td>
            </tr>
         </tbody>
        </table>
        </div>
        <br>
    {% empty %}
        <div class="text-center">
            <h1><strong><u>NO SEASON FOUND</u></strong></h1>
        </div>
    {% endfor %}
    </div>


    <div class="container p-3 my-3 border" style="background-color: lightgray">
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1{% if request.GET.nameform %}&nameform={{ request.GET.nameform }}{% endif %}">&laquo; <button type="button" class="btn btn-info">First</button></a>
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.nameform %}&nameform={{ request.GET.nameform }}{% endif %}"><button type="button" class="btn btn-primary">Previous</button></a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.nameform %}&nameform={{ request.GET.nameform }}{% endif %}"><button type="button" class="btn btn-primary">Next</button></a>
                <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.nameform %}&nameform={{ request.GET.nameform }}{% endif %}"><button type="button" class="btn btn-info">Last</button> &raquo;</a>
            {% endif %}
        </span>
        </div>
    </div>

{% endblock %}

waterpark/templates/waterpark/staff/detail/staff_tiket_detail.html
{% extends 'navbase.html' %}

{% block title %}STAFF: Tickets results{% endblock %}

{% block bodybase %}
    <div class="text-center" style="background-color: lightgray">
        <h1><strong><u>TICKETS RESULTS:</u></strong></h1><br>
        <p><strong>Today: "{% now 'd-M-Y' %}" --> {% now 'D' %}</strong></p>
        <a href="{% url 'waterpark:staff-search-tiket-for-user-results' %}?nameform={{ request.GET.nameform }}"><button type="button" class="btn btn-light">Get all tickets of {{ request.GET.nameform }}</button></a><br><br>
        <a href="{% url 'waterpark:staff-search-tiket-for-user-results-today' %}?nameform={{ request.GET.nameform }}"><button type="button" class="btn btn-success">Get "{% now 'd-M-Y' %}" ticket of {{ request.GET.nameform }}</button></a><br><br>
        <a href="{% url 'waterpark:staff-search-tiket-for-user' %}"><button type="button" class="btn btn-info">Back</button></a>
        </div>
    <div class="container p-3 my-3 bg-dark text-white">
    {% for tiket in tiket_list %}
        <br>
        <div class="container p-3 my-3 border">
        <table class="table table-striped table-dark">
          <thead>
            <tr>
                <th scope="col"><strong>TICKET FIELDS</strong></th>
              <th scope="col"><strong>INFO</strong></th>
            </tr>
          </thead>
        <tbody>
            <tr>
            <th scope="row">CUSTOMER USERNAME:</th>
             <td>{{ tiket.customer.get_username }}</td>
            </tr>
            <tr>
            <th scope="row">CUSTOMER BIRTHDAY:</th>
             <td>{{ tiket.customer.birth_date }}</td>
            </tr>
            <tr>
            <th scope="row">CUSTOMER GENDER:</th>
             <td>{{ tiket.customer.gender }}</td>
            </tr>
            <tr>
            <th scope="row">CUSTOMER EMAIL:</th>
             <td>{{ tiket.customer.email }}</td>
            </tr>
            {% if tiket.customer.first_name %}
                <tr>
                <th scope="row">CUSTOMER FIRST NAME:</th>
                <td>{{ tiket.customer.first_name }}</td>
                </tr>
            {% endif %}
            {% if tiket.customer.last_name %}
                <tr>
                <th scope="row">CUSTOMER LAST NAME:</th>
                <td>{{ tiket.customer.last_name }}</td>
                </tr>
            {% endif %}
            <tr>
            <th scope="row">TICKET ID:</th>
             <td>{{ tiket.tiket_slug }}</td>
            </tr>
            <tr>
            <th scope="row">DATE OF PURCHASE:</th>
             <td>{{ tiket.date_of_purchase }}</td>
            </tr>
            <tr>
            <th scope="row">PRICE:</th>
             <td>${{ tiket.cost }}</td>
            </tr>
            <tr>
            <th scope="row">VALIDITY DAY:</th>
             <td>{{ tiket.validity_day }}</td>
            </tr>
         </tbody>
        </table>
        </div>
        <br>
    {% empty %}
        <div class="text-center">
            <h1><strong><u>NO TICKETS FOUND</u></strong></h1>
        </div>
    {% endfor %}
    </div>


    <div class="container p-3 my-3 border" style="background-color: lightgray">
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1{% if request.GET.nameform %}&nameform={{ request.GET.nameform }}{% endif %}">&laquo; <button type="button" class="btn btn-info">First</button></a>
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.nameform %}&nameform={{ request.GET.nameform }}{% endif %}"><button type="button" class="btn btn-primary">Previous</button></a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.nameform %}&nameform={{ request.GET.nameform }}{% endif %}"><button type="button" class="btn btn-primary">Next</button></a>
                <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.nameform %}&nameform={{ request.GET.nameform }}{% endif %}"><button type="button" class="btn btn-info">Last</button> &raquo;</a>
            {% endif %}
        </span>
        </div>
    </div>

{% endblock %}