userpark/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from userpark.views import UserCreateView, CustomerSignUpView, StaffSignUpView, UserLoginView, UserProfileView, UserUpdatePropicView, UserUpdateFirstNameView, UserUpdateLastNameView, UserUpdateGenderView, UserUpdateEmailView, UserUpdateBirthDateView, UserUpdatePasswordView, UserDeleteProfileView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'userpark'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('user_create/', UserCreateView.as_view(), name='user-create'),
    path('user_create/customer_sign_in/', CustomerSignUpView.as_view(), name='customer-create'),
    path('user_create/staff_sign_in/', StaffSignUpView.as_view(), name='staff-create'),
    path('user_profile/', UserProfileView.as_view(), name='user-profile'),
    path('user_profile/<slug:slug>/update_propic/', UserUpdatePropicView.as_view(), name='user-profile-update-propic'),   # HERE
    path('user_profile/<slug:slug>/update_first_name/', UserUpdateFirstNameView.as_view(), name='user-profile-update-firstname'),
    path('user_profile/<slug:slug>/update_last_name/', UserUpdateLastNameView.as_view(), name='user-profile-update-lastname'),
    path('user_profile/<slug:slug>/update_gender/', UserUpdateGenderView.as_view(), name='user-profile-update-gender'),
    path('user_profile/<slug:slug>/update_email/', UserUpdateEmailView.as_view(), name='user-profile-update-email'),
    path('user_profile/<slug:slug>/update_birth_date/', UserUpdateBirthDateView.as_view(), name='user-profile-update-birthdate'),
    path('user_profile/<slug:slug>/update_password/', UserUpdatePasswordView.as_view(), name='user-profile-update-password'),
    path('user_profile/<slug:slug>/delete_profile/', UserDeleteProfileView.as_view(), name='user-profile-delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterland/urls.py
from django.contrib import admin
from django.urls import path, include
from waterland.views import HomeView, WaterlandParkView, AboutUsView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('waterpark/', include('waterpark.urls')),
    path('userpark/', include('userpark.urls')),
    path('reviewpark/', include('reviewpark.urls')),
    path('', HomeView.as_view(), name='home'),
    path('waterland_park', WaterlandParkView.as_view(), name='waterland-park-info-showcase'),
    path('about_us', AboutUsView.as_view(), name='waterland-about-us'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userpark/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import date, timedelta
from PIL import Image
from django.template.defaultfilters import slugify
import uuid as UUID_LIB

AbstractUser._meta.get_field('email')._unique = True
AbstractUser._meta.get_field('email').blank = False
AbstractUser._meta.get_field('email').null = False
AbstractUser._meta.get_field('username')._unique = True

# Where to upload pics of the user into user directory


def media_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance, filename)


# Create your models here.


class User(AbstractUser):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, help_text="Are you male or female?", null=True, default=None)
    birth_date = models.DateField(help_text="Place your birthday here", null=True,
                                  validators=[MaxValueValidator(limit_value=date.today()-timedelta(days=(365*7))),
                                              MinValueValidator(limit_value=date.today()-timedelta(days=(365*100)))], default=None)
    staff_assigned_code = models.CharField(max_length=5, help_text="Place your staff code here", null=True, unique=True, default=None)
    is_staff_member = models.BooleanField(default=False)
    propic = models.ImageField(upload_to=media_directory_path, blank=True, null=True,
                               default=None, help_text='Add your profile picture here', verbose_name='Picture Profile')
    slug = models.SlugField(null=False, unique=True)  # max length disabled

    def __str__(self):
        return f'{self.username} - Profile'

    def save(self, *args, **kwargs):
        if self.is_staff:
            self.is_staff_member = True

        if not self.slug:
            self.slug = slugify(str(UUID_LIB.uuid1()))
        super().save(*args, **kwargs)  # Save all at database

        if self.propic:    # Using Pillow Package to resize the propic
            img = Image.open(self.propic.path)
            if img.height > 200 or img.width > 200:
                output_size = (200, 200)
                img.thumbnail(output_size)
                img.save(self.propic.path)


class StaffAuthTable(models.Model):  # External populated table for hired staff
    code = models.CharField(max_length=5, null=False, blank=False, unique=True)
    key = models.CharField(max_length=20, null=False, blank=False, default='createstaffuser')
    is_used = models.BooleanField(blank=False, null=False, default=False)

    class Meta:
        verbose_name_plural = 'Staff-Auth-Table'

    def __str__(self):
        return f'{self.code}-{self.key}-{self.is_used}'

userpark/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from userpark.models import User as myUser
from userpark.models import StaffAuthTable
from datetime import date, timedelta
from django.contrib.auth.password_validation import validate_password


class DateInput(forms.DateInput):
    input_type = 'date'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.attrs.setdefault('min', str(date.today() - timedelta(days=(365 * 100))))
        self.attrs.setdefault('max', str(date.today() - timedelta(days=(365 * 7))))


class CustomerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = myUser
        fields = ['username', 'first_name', 'last_name', 'email', 'gender', 'birth_date']
        fields_required = ['username', 'email', 'gender', 'birth_date']
        widgets = {
            'birth_date': DateInput(),
        }

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_staff_member = False
        user.staff_assigned_code = None
        user.save()
        return user


class StaffSignUpForm(UserCreationForm):
    staff_key = forms.CharField(max_length=20, help_text='Write here the key to create your staff account',
                                widget=forms.PasswordInput())

    class Meta(UserCreationForm.Meta):
        model = myUser
        fields = ['username', 'first_name', 'last_name', 'email', 'gender', 'birth_date', 'staff_assigned_code',
                  'staff_key']
        fields_required = ['username', 'email', 'staff_assigned_code', 'gender', 'birth_date', 'staff_key']
        widgets = {
            'birth_date': DateInput(),
        }

    def clean(self):
        cleaned_data = super(StaffSignUpForm, self).clean()
        code = cleaned_data.get('staff_assigned_code')  # retrive staff assigned code from the form
        keystaff = cleaned_data.get('staff_key')  # retrive staff key from the form
        auth = StaffAuthTable.objects.filter(code=code, key=keystaff,
                                             is_used=False)  # get instance, must be just one result
        if auth.count():
            auth_dict = auth.values('code', 'key')[0]  # get dict of the instance
            if keystaff == auth_dict['key'] and code == auth_dict['code']:
                if cleaned_data.get('password1') == cleaned_data.get('password2') and self.is_valid():
                    auth.update(is_used=True)
            else:
                self.add_error('staff_key', u'Invalid combination!')
                self.add_error('staff_assigned_code', u'Invalid combination!')
        else:
            self.add_error('staff_key', u'Invalid combination!')
            self.add_error('staff_assigned_code', u'Invalid combination!')
        return cleaned_data

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_staff_member = True
        user.save()
        return user


# Update profile form


class UpdateBirthdateForm(forms.ModelForm):
    class Meta:
        model = myUser
        fields = ['birth_date']
        widgets = {
            'birth_date': DateInput(),  # Complete range
        }


class UpdatePasswordForm(forms.ModelForm):
    current_password = forms.CharField(max_length=4096, widget=forms.PasswordInput(),
                                       help_text='Type your current password here')  # 4096 django password length
    repeat_new_password = forms.CharField(max_length=4096, widget=forms.PasswordInput(),
                                          help_text='Type your new password again here')  # 4096 django password length

    class Meta:
        model = myUser
        fields = ['current_password', 'password', 'repeat_new_password']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean(self):
        cleaned_data = super(UpdatePasswordForm, self).clean()
        old_p = cleaned_data.get('current_password')
        p = cleaned_data.get('password')
        pp = cleaned_data.get('repeat_new_password')
        if old_p == p:
            self.add_error('current_password', u'Cannot use the current password as the new one')
            self.add_error('password', u'Cannot use the current password as the new one')
        if p != pp:
            self.add_error('password', u'Different password typing')
            self.add_error('repeat_new_password', u'Different password typing')
        else:
            validate_password(p)
        return cleaned_data

userpark/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.hashers import check_password, make_password
from userpark.models import User as myUser, StaffAuthTable
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView
from userpark.forms import CustomerSignUpForm, StaffSignUpForm, UpdateBirthdateForm, UpdatePasswordForm
from django.contrib.auth import views as auth_views
from django.contrib import messages
from django.contrib.auth.signals import user_logged_out
from django.dispatch import receiver


@receiver(user_logged_out)
def on_user_logged_out(sender, request, **kwargs):
    messages.add_message(request, messages.SUCCESS, 'Logged Out')


# Create your views here.

# User Sin-In and Log-In view


class UserCreateView(TemplateView):
    template_name = 'userpark/user_create.html'


class UserLoginView(SuccessMessageMixin, auth_views.LoginView):
    success_message = 'Logged In'


class CustomerSignUpView(SuccessMessageMixin, CreateView):
    model = myUser  # Where to save
    form_class = CustomerSignUpForm
    template_name = 'userpark/customer_signin.html'
    success_url = reverse_lazy('home')
    success_message = 'Your customer user has been created'


class StaffSignUpView(SuccessMessageMixin, CreateView):
    model = myUser  # Where to save
    form_class = StaffSignUpForm
    template_name = 'userpark/sfaff_signin.html'
    success_url = reverse_lazy('home')
    success_message = 'Your staff user has been created'

    def form_invalid(self, form):
        if form.cleaned_data.get('staff_assigned_code'):
            c = form.cleaned_data.get('staff_assigned_code')
            keys = StaffAuthTable.objects.filter(code=c)
            keys.update(is_used=False)
        return super().form_invalid(form)


# User profile view


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'userpark/profile/profile_detail.html'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'


# Update user info view


class UserUpdatePropicView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = myUser
    fields = ['propic']
    template_name = 'userpark/profile/update_propic.html'
    success_url = reverse_lazy('userpark:user-profile')
    success_message = 'Profile picture updated'
    slug_field = 'slug'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'


class UserUpdateFirstNameView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = myUser
    fields = ['first_name']
    template_name = 'userpark/profile/update_first_name.html'
    success_url = reverse_lazy('userpark:user-profile')
    success_message = 'First name updated'
    slug_field = 'slug'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'


class UserUpdateLastNameView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = myUser
    fields = ['last_name']
    template_name = 'userpark/profile/update_last_name.html'
    success_url = reverse_lazy('userpark:user-profile')
    success_message = 'Last name updated'
    slug_field = 'slug'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'


class UserUpdateEmailView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = myUser
    fields = ['email']
    template_name = 'userpark/profile/update_email.html'
    success_url = reverse_lazy('userpark:user-profile')
    success_message = 'Email updated'
    slug_field = 'slug'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'


class UserUpdateGenderView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = myUser
    fields = ['gender']
    template_name = 'userpark/profile/update_gender.html'
    success_url = reverse_lazy('userpark:user-profile')
    success_message = 'Gender updated'
    slug_field = 'slug'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'


class UserUpdateBirthDateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = myUser
    form_class = UpdateBirthdateForm
    template_name = 'userpark/profile/update_birth_date.html'
    success_url = reverse_lazy('userpark:user-profile')
    success_message = 'Birth date updated'
    slug_field = 'slug'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'


class UserUpdatePasswordView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = myUser
    form_class = UpdatePasswordForm
    template_name = 'userpark/profile/update_password.html'
    success_url = reverse_lazy('userpark:user-profile')
    success_message = 'Password updated'
    slug_field = 'slug'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'

    def form_valid(self, form):
        currentpassword = self.request.user.password
        currentpasswordentered = form.cleaned_data.get("current_password")
        matchcheck = check_password(currentpasswordentered, currentpassword)
        if matchcheck:
            self.object = form.save(commit=False)
            self.object.password = make_password(self.object.password)
            self.object.save()
            return super().form_valid(form)
        else:
            messages.warning(self.request, 'Current password is not the expected one!')
            return self.form_invalid(form)


# User delete view


class UserDeleteProfileView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = myUser
    template_name = 'userpark/profile/delete_profile.html'
    success_url = reverse_lazy('home')
    success_message = 'Profile deleted'
    slug_field = 'slug'
    login_url = 'userpark:login'  # Redirect Login needed
    redirect_field_name = 'redirect_to'

userpark/templates/userpark/profile/delete_profile.html
{% extends 'navbase.html' %}

{% block title %}Profile: {{ user.username }} delete?{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 border">
        <form method="post">{% csrf_token %}
            <p class="font-weight-bold">Are you sure you want to delete your profile "{{ object.username }}"?</p>
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Yes, delete my profile</button>
        <a href="{% url 'userpark:user-profile' %}"> <button type="button" class="btn btn-dark">Back</button> </a>
        </form>
    </div>

{% endblock %}

userpark/templates/userpark/profile/profile_detail.html
{% extends 'navbase.html' %}
{% load static %}

{% block title %}Profile: {{ user.username }}{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 border">
        <h1 class="display-4"><u>PROFILE</u><br><em><small>{{ user.username }}</small></em></h1><br>
        <table class="table table-striped">
        <thead>
        <tr>
        <th scope="col">About you</th>
        <th scope="col">Info</th>
        <th scope="col">Update</th>
        </tr>
        </thead>
        <tbody>
        {% if not user.is_staff_member %}
            <tr>
            <th scope="row">Photo</th>
                {% if not user.propic %}
                    <td><img src="{% static 'img/generic_user_profile.png' %}" alt="propic" class="img-thumbnail"></td>
                {% else %}
                    <td><img src="/media/{{ MEDIA_URL }}{{ user.propic }}" alt="propic" class="img-thumbnail"></td>
                {% endif %}
            <td><a href="{% url 'userpark:user-profile-update-propic' user.slug %}"><button type="button" class="btn btn-info">UPDATE</button></a></td>
            </tr>
        {% endif %}
        <tr>
        <th scope="row">First Name</th>
        <td>{{ user.first_name }}</td>
        <td><a href="{% url 'userpark:user-profile-update-firstname' user.slug %}"><button type="button" class="btn btn-info">UPDATE</button></a></td>
        </tr>
        <tr>
        <th scope="row">Last Name</th>
        <td>{{ user.last_name }}</td>
        <td><a href="{% url 'userpark:user-profile-update-lastname' user.slug %}"><button type="button" class="btn btn-info">UPDATE</button></a></td>
        </tr>
        <tr>
        <th scope="row">Gender</th>
        <td>{{ user.gender }}</td>
        <td><a href="{% url 'userpark:user-profile-update-gender' user.slug %}"><button type="button" class="btn btn-info">UPDATE</button></a></td>
        </tr>
        <tr>
        <th scope="row">Email</th>
        <td>{{ user.email }}</td>
        <td><a href="{% url 'userpark:user-profile-update-email' user.slug %}"><button type="button" class="btn btn-info">UPDATE</button></a></td>
        </tr>
        <tr>
        <th scope="row">Birthday</th>
        <td>{{ user.birth_date }}</td>
        <td><a href="{% url 'userpark:user-profile-update-birthdate' user.slug %}"><button type="button" class="btn btn-info">UPDATE</button></a></td>
        </tr>
        {% if user.is_staff_member and not user.is_staff %}
            <tr>
            <th scope="row">Staff code</th>
            <td>{{ user.staff_assigned_code }}</td>
            <td>-</td>
            </tr>
        {% endif %}
        {% if user.is_staff %}
            <tr>
            <th scope="row">Staff code</th>
            <td>WEBSITE ADMINISTRATOR</td>
            <td>-</td>
            </tr>
        {% endif %}
        <tr>
        <th scope="row">Sing In date</th>
        <td>{{ user.date_joined }}</td>
        <td>-</td>
        </tr>
        <tr>
        <th scope="row">Last login</th>
        <td>{{ user.last_login }}</td>
        <td>-</td>
        </tr>
        </tbody>
        </table>
    <br>
    <a href="{% url 'userpark:user-profile-update-password' user.slug %}"> <button type="button" class="btn btn-warning">UPDATE PASSWORD</button> </a>
    <br><br>
    <a href="{% url 'userpark:user-profile-delete' user.slug %}"> <button type="button" class="btn btn-danger">DELETE MY PROFILE</button> </a>
    </div>
    <br>


{% endblock %}

userpark/templates/userpark/profile/update_birth_date.html
{% extends 'navbase.html' %}
{% load crispy_forms_filters %}

{% block title %}Profile: {{ user.username }}, update birth date{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <h1 class="display-4">UPDATE BIRTHDAY:</h1>
        <p>CURRENT BIRTH DATE: {{ user.birth_date }}</p>
        <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'userpark:user-profile' %}"> <button type="button" class="btn btn-primary">Back</button> </a>
        </form>
    </div>
    <br>

{% endblock %}

userpark/templates/userpark/profile/update_email.html
{% extends 'navbase.html' %}
{% load crispy_forms_filters %}

{% block title %}Profile: {{ user.username }}, update email{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <h1 class="display-4">UPDATE EMAIL:</h1>
        <p>CURRENT FIRST NAME: {{ user.email }}</p>
        <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'userpark:user-profile' %}"> <button type="button" class="btn btn-primary">Back</button> </a>
        </form>
    </div>
    <br>

{% endblock %}

userpark/templates/userpark/profile/update_first_name.html
{% extends 'navbase.html' %}
{% load crispy_forms_filters %}

{% block title %}Profile: {{ user.username }}, update first name{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <h1 class="display-4">UPDATE FIRST NAME:</h1>
        <p>CURRENT FIRST NAME: {{ user.first_name }}</p>
        <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'userpark:user-profile' %}"> <button type="button" class="btn btn-primary">Back</button> </a>
        </form>
    </div>
    <br>

{% endblock %}

userpark/templates/userpark/profile/update_gender.html
{% extends 'navbase.html' %}
{% load crispy_forms_filters %}

{% block title %}Profile: {{ user.username }}, update gender{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <h1 class="display-4">UPDATE GENDER:</h1>
        <p>CURRENT GENDER: {{ user.gender }}</p>
        <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'userpark:user-profile' %}"> <button type="button" class="btn btn-primary">Back</button> </a>
        </form>
    </div>
    <br>

{% endblock %}

userpark/templates/userpark/profile/update_last_name.html
{% extends 'navbase.html' %}
{% load crispy_forms_filters %}

{% block title %}Profile: {{ user.username }}, update last name{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <h1 class="display-4">UPDATE LAST NAME:</h1>
        <p>CURRENT LAST NAME: {{ user.last_name }}</p>
        <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'userpark:user-profile' %}"> <button type="button" class="btn btn-primary">Back</button> </a>
        </form>
    </div>
    <br>

{% endblock %}

userpark/templates/userpark/profile/update_password.html
{% extends 'navbase.html' %}
{% load crispy_forms_filters %}

{% block title %}Profile: {{ user.username }}, update password{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <h1 class="display-4">UPDATE PASSWORD:</h1>
        <p>Place your current password to verify you, after place new one</p>
        <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'userpark:user-profile' %}"> <button type="button" class="btn btn-primary">Back</button> </a>
        </form>
    </div>
    <br>

{% endblock %}

userpark/templates/userpark/profile/update_propic.html
{% extends 'navbase.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}Profile: {{ user.username }}, update propic{% endblock %}

{% block bodybase %}

    <div class="container p-3 my-3 bg-dark text-white">
        <h1 class="display-4">UPDATE PROFILE PICTURE:</h1>
        {% if not user.propic %}
            <img src="{% static 'img/generic_user_profile.png' %}" alt="current_propic" class="img-thumbnail">
        {% else %}
            <img src="/media/{{ MEDIA_URL }}{{ user.propic }}" alt="current_propic" class="img-thumbnail">
        {% endif %}
        <p>CURRENT PICTURE PROFILE</p>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'userpark:user-profile' %}"> <button type="button" class="btn btn-primary">Back</button> </a>
        </form>
    </div>
    <br>

{% endblock %}