reviewpark/urls.py
from django.urls import path
from reviewpark.views import FeedbackCreateView, FeedbackListView, FaqCreateView, FaqMineView, FaqListView, FaqStaffListView, FaqStaffDeleteView, FaqStaffAnswareView, FeedbackStaffDeleteView, SearchContextFaqView, SearchFeedbackByStarsView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'reviewpark'

urlpatterns = [

    path('leavefeedback/', FeedbackCreateView.as_view(), name='leave-feedback'),
    path('feedback/', FeedbackListView.as_view(), name='feedback-list'),
    path('feedback/staff/<int:pk>/delete_feedback/', FeedbackStaffDeleteView.as_view(), name='feedback-staff-delete'),
    path('faq/ask/', FaqCreateView.as_view(), name='faq-ask'),
    path('faq/mine/', FaqMineView.as_view(), name='faq-mine'),
    path('faq/', FaqListView.as_view(), name='faq'),
    path('faq/staff_list/', FaqStaffListView.as_view(), name='faq-staff-list'),
    path('faq/staff_list/<int:pk>/delete_faq/', FaqStaffDeleteView.as_view(), name='faq-staff-delete'),
    path('faq/staff_list/<int:pk>/answer_faq/', FaqStaffAnswareView.as_view(), name='faq-staff-answare'),
    path('faq/search/', SearchContextFaqView.as_view(), name='faq-search-context'),
    path('feedback/search/', SearchFeedbackByStarsView.as_view(), name='feedback-search-stars'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userpark/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from userpark.views import UserCreateView, CustomerSignUpView, StaffSignUpView, UserLoginView, UserProfileView, UserUpdatePropicView, UserUpdateFirstNameView, UserUpdateLastNameView, UserUpdateGenderView, UserUpdateEmailView, UserUpdateBirthDateView, UserUpdatePasswordView, UserDeleteProfileView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'userpark'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('user_create/', UserCreateView.as_view(), name='user-create'),
    path('user_create/customer_sign_in/', CustomerSignUpView.as_view(), name='customer-create'),
    path('user_create/staff_sign_in/', StaffSignUpView.as_view(), name='staff-create'),
    path('user_profile/', UserProfileView.as_view(), name='user-profile'),
    path('user_profile/<slug:slug>/update_propic/', UserUpdatePropicView.as_view(), name='user-profile-update-propic'),   # HERE
    path('user_profile/<slug:slug>/update_first_name/', UserUpdateFirstNameView.as_view(), name='user-profile-update-firstname'),
    path('user_profile/<slug:slug>/update_last_name/', UserUpdateLastNameView.as_view(), name='user-profile-update-lastname'),
    path('user_profile/<slug:slug>/update_gender/', UserUpdateGenderView.as_view(), name='user-profile-update-gender'),
    path('user_profile/<slug:slug>/update_email/', UserUpdateEmailView.as_view(), name='user-profile-update-email'),
    path('user_profile/<slug:slug>/update_birth_date/', UserUpdateBirthDateView.as_view(), name='user-profile-update-birthdate'),
    path('user_profile/<slug:slug>/update_password/', UserUpdatePasswordView.as_view(), name='user-profile-update-password'),
    path('user_profile/<slug:slug>/delete_profile/', UserDeleteProfileView.as_view(), name='user-profile-delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterland/urls.py
from django.contrib import admin
from django.urls import path, include
from waterland.views import HomeView, WaterlandParkView, AboutUsView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('waterpark/', include('waterpark.urls')),
    path('userpark/', include('userpark.urls')),
    path('reviewpark/', include('reviewpark.urls')),
    path('', HomeView.as_view(), name='home'),
    path('waterland_park', WaterlandParkView.as_view(), name='waterland-park-info-showcase'),
    path('about_us', AboutUsView.as_view(), name='waterland-about-us'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waterpark/urls.py
from django.urls import path
from waterpark.views import CustomerServiceMenuView, CustomerBuyTiketView, CustomerBuySeasonPassView, CustomerTiketListView, CustomerSeasonPassListView, StaffManageTiketMainView, StaffManageSeasonpassMainView, SearchTiketByDateListView, SearchTiketByYearListView, SearchTiketByRangeListView, SearchSeasonpassByYearListView, SearchCustomerTiketView, SearchCustomerSeasonpassView, SearchCustomerTiketListView, SearchCustomerSeasonpassListView, GetTiketTodayView, GetTiketTodayStaffView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'waterpark'

urlpatterns = [

    path('tickets&seasonpass/', CustomerServiceMenuView.as_view(), name='customerservices'),
    path('tickets&seasonpass/buy_a_ticket/', CustomerBuyTiketView.as_view(), name='customer-buy-tiket'),
    path('tickets&seasonpass/buy_a_seasonpass/', CustomerBuySeasonPassView.as_view(), name='customer-buy-seasonpass'),
    path('tickets&seasonpass/my_tickets/', CustomerTiketListView.as_view(), name='customer-tiket-list'),
    path('tickets&seasonpass/my_seasonpass/', CustomerSeasonPassListView.as_view(), name='customer-seasonpass-list'),
    path('ticket_management/', StaffManageTiketMainView.as_view(), name='staff-manage-tiket-main'),
    path('seasonpass_management/', StaffManageSeasonpassMainView.as_view(), name='staff-manage-seasonpass-main'),
    path('ticket_management/search_by_date/', SearchTiketByDateListView.as_view(), name='staff-manage-tiket-by-day'),
    path('ticket_management/search_by_year/', SearchTiketByYearListView.as_view(), name='staff-manage-tiket-by-year'),
    path('ticket_management/search_by_range/', SearchTiketByRangeListView.as_view(), name='staff-manage-tiket-by-range'),
    path('seasonpass_management/search_by_year/', SearchSeasonpassByYearListView.as_view(), name='staff-manage-seasonpass-by-year'),
    path('customer_search_ticket/', SearchCustomerTiketView.as_view(), name='staff-search-tiket-for-user'),
    path('customer_search_ticket/customer/', SearchCustomerTiketListView.as_view(), name='staff-search-tiket-for-user-results'),
    path('customer_search_seasonpass/', SearchCustomerSeasonpassView.as_view(), name='staff-search-seasonpass-for-user'),
    path('customer_search_seasonpass/customer/', SearchCustomerSeasonpassListView.as_view(), name='staff-search-seasonpass-for-user-results'),
    path('tickets&seasonpass/my_tickets/today', GetTiketTodayView.as_view(), name='customer-tiket-list-today'),
    path('customer_search_ticket/customer/today', GetTiketTodayStaffView.as_view(), name='staff-search-tiket-for-user-results-today'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about_us.html
{% extends 'navbase.html' %}
{% load static %}

{% block title %}WaterLand, about us{% endblock %}

{% block bodybase %}

    <div class="container pt-3">
        <h2 style="color: darkslategray"><u>About Us</u></h2>
        <p class="h4" style="color: darkslategray; text-align: justify">{% lorem %}</p>
    </div><br>

    <div class="container p-3 my-3 border">
        <h2 style="color: darkslategray"><u>AVAILABLE CONTACTS</u></h2><br>
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row"><img src="{% static 'img/mailicon_30.png' %}" alt="mail"></th>
              <td><p class="h4" style="color: darkslategray">E-mail: <br> waterland@waterpark.com</p></td>
            </tr>
            <tr>
              <th scope="row"><img src="{% static 'img/tel_20.png' %}" alt="phone"></th>
              <td><p class="h4" style="color: darkslategray">Phone: <br> 555-4337291</p></td>
            </tr>
          </tbody>
        </table>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
          crossorigin="anonymous">

    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>

    <title> {% block title %} {% endblock %} </title>

        <div id="logo" class="text-center">
        <a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" class="rounded" alt= "logo"></a>
        </div>

    {% block head %} {% endblock %}

  </head>
  <body style="background-color:#E5FFFF;">
    {% block body %} {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
            crossorigin="anonymous"></script>

    <!-- <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> -->
    <script src="{% static 'js/sweetalertmin.js' %}"></script>
    <script>
        {% if messages %}
            {% for msg in messages %}
                {% if msg.tags == 'success' %}
                    swal({
                        title: '{{ msg }}',
                        text: 'Click ok to continue',
                        icon: 'success',
                        button: 'OK',
                    });
                {% endif %}
                {% if msg.tags == 'warning' %}
                    swal({
                        title: '{{ msg }}',
                        text: 'Click ok to continue',
                        icon: 'warning',
                        button: 'OK',
                    });
                {% endif %}
            {% endfor %}
        {% endif %}
    </script>

    {% block javascript %} {% endblock %}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
{% extends 'navbase.html' %}
{% load static %}

{% block title %}WaterLand Homepage{% endblock %}

{% block bodybase %}

    <div class="d-block d-sm-none" style="background: deepskyblue">
        <div class="text-center">
            <p class="text-uppercase" style="color: honeydew"><strong>waterland mobile phone website</strong></p>
            <p style="color: honeydew"><strong>(tap [≡] to scroll down the navbar)</strong></p>
        </div>
    </div>

    <div class="d-none d-md-block d-lg-none" style="background: deepskyblue">
        <div class="text-center">
            <p class="text-uppercase" style="color: honeydew"><strong>waterland tablet website</strong></p>
            <p style="color: honeydew"><strong>(tap [≡] to scroll down the navbar)</strong></p>
        </div>
    </div>

    <div id="homeCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#homeCarousel" data-slide-to="1"></li>
        <li data-target="#homeCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'img/1.jpg' %}" class="d-block w-100" alt="firstpic">
          <div class="carousel-caption d-none d-md-block">
            <h5 style="color:black ; ">A lot of swimming pools for you</h5>
            <p style="color:black ; ">Spend your holidays here!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/2.jpg' %}" class="d-block w-100" alt="secondpic">
          <div class="carousel-caption d-none d-md-block">
            <h5 style="color:black ; ">WaterLand is family-friendly!</h5>
            <p style="color:black ; ">Children and their family can play together</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/3.jpg' %}" class="d-block w-100" alt="thirdpic">
          <div class="carousel-caption d-none d-md-block">
            <h5 style="color:black ; ">Together</h5>
              <p style="color:black ; "><strong>in our exciting slides!</strong></p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-target="#homeCarousel" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-target="#homeCarousel" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </button>
    </div>

{% endblock %}

templates/navbase.html
{% extends 'base.html' %}
{% load static %}


{% block head %}

    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
      <a class="navbar-brand" href="{% url 'home' %}">WATERLAND HOMEPAGE</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'waterland-park-info-showcase' %}">Waterland Park <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_authenticated %}
              {% if user.is_staff_member %}
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                Staff {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'userpark:user-profile' %}">Profile</a>
                <a class="dropdown-item" href="{% url 'waterpark:staff-manage-tiket-main' %}">History management Ticket</a>
                <a class="dropdown-item" href="{% url 'waterpark:staff-search-tiket-for-user' %}">Detail Ticket</a>
                <a class="dropdown-item" href="{% url 'waterpark:staff-manage-seasonpass-main' %}">History management SeasonPass</a>
                <a class="dropdown-item" href="{% url 'waterpark:staff-search-seasonpass-for-user' %}">Detail SeasonPass</a>
                <a class="dropdown-item" href="{% url 'reviewpark:faq-staff-list' %}">Answer to FAQ</a>
                <a class="dropdown-item" href="{% url 'userpark:logout' %}">Logout</a>
                </div>
                </li>
            {% else %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
             Hi {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'userpark:user-profile' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'waterpark:customerservices' %}">Buy Tickets & SeasonPass</a>
              <a class="dropdown-item" href="{% url 'waterpark:customer-tiket-list' %}">My Tickets</a>
              <a class="dropdown-item" href="{% url 'waterpark:customer-seasonpass-list' %}">My Season Pass</a>
              <a class="dropdown-item" href="{% url 'reviewpark:faq-ask' %}">Ask a FAQ</a>
              <a class="dropdown-item" href="{% url 'reviewpark:faq-mine' %}">My FAQ</a>
              <a class="dropdown-item" href="{% url 'userpark:logout' %}">Logout</a>
            </div>
          </li>
          {% endif %}
          {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'userpark:user-create' %}">Sign in</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'userpark:login' %}">Log in</a>
            </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
              Further link
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'reviewpark:feedback-list' %}">Feedback</a>
              <a class="dropdown-item" href="{% url 'reviewpark:faq' %}">FAQ</a>
              <a class="dropdown-item" href="{% url 'waterland-about-us' %}">About Us</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    {% block headbase %} {% endblock %}

{% endblock %}


{% block body %}

    {% block bodybase %}{% endblock %}

        <footer>
            <div class="card bg-dark text-white">
              <img src="{% static 'img/footer.jpg' %}" class="card-img" alt="footerimg">
              <div class="card-img-overlay">
                <h3 class="card-title" style="color:#b8cdda ; ">WATERLAND PARK</h3>
                  <br>
                <p class="card-text" style="color:#b8cdda ; ">Navigation and further information above</p>
              </div>
            </div>
        </footer>

{% endblock %}

templates/waterland_park.html
{% extends 'navbase.html' %}
{% load static %}

{% block title %}WaterLand, about the acquapark{% endblock %}

{% block bodybase %}
    <br>
    <div class="text-center">
        <img src="{% static 'img/favicon.ico' %}" alt="favicon">
    </div>
    <br>
    <div class="container-sm border" style="text-align: justify">
        <h2><img src="{% static 'img/logo.png' %}" alt="logo"> <br> <small class="text-muted"><u>(History of the acquapark)</u></small></h2>
        <p class="h4" style="color: darkslategray">{% lorem %}</p>
    </div>
    <div class="text-center">
        <img src="{% static 'img/separator_text.png' %}" alt="separator">
    </div>
    <br>
    <div class="container-sm border" style="text-align: justify">
        <h2><img src="{% static 'img/logo.png' %}" alt="logo"> <br> <small class="text-muted"><u>(Our swimming pools)</u></small></h2>
        <p class="h4" style="color: darkslategray">{% lorem %}<br><br>The park also offers indoor swimming pools and a sauna for the winter months.</p>
    </div>
    <div class="text-center">
        <img src="{% static 'img/separator_text.png' %}" alt="separator">
    </div>
    <br>
    <div class="container-sm border" style="text-align: justify">
        <h2><img src="{% static 'img/logo.png' %}" alt="logo"> <br> <small class="text-muted"><u>(Daily tickets, SeasonPass and price)</u></small></h2>
        <p class="h4" style="color: darkslategray">You can buy a daily ticket or enjoy all the year here with us with the season pass, when you buy a season pass it shall be used for all the current year, about daily ticket you need to choose a date.<br><br>Daily ticket price: $15<br>Season pass price: $125</p>
    </div>
    <div class="text-center">
        <img src="{% static 'img/separator_text.png' %}" alt="separator">
    </div>
    <br>
    <div class="container-sm border" style="text-align: justify">
        <h2><img src="{% static 'img/logo.png' %}" alt="logo"> <br> <small class="text-muted"><u>(Opening times)</u></small></h2>
        <p class="h4" style="color: darkslategray">We are open all days<br><br>-From 8.00am-<br>-Until 18.00pm-<br><br>In the summer we are open until 20.00pm</p>
    </div>
    <div class="text-center">
        <img src="{% static 'img/separator_text.png' %}" alt="separator">
    </div>
    <br>
    <div class="container-sm border" style="text-align: justify">
        <h2><img src="{% static 'img/logo.png' %}" alt="logo"> <br> <small class="text-muted"><u>(How to find us)</u></small></h2>
        <p class="h4" style="color: darkslategray">{% lorem %}</p>
    </div>
    <br>
    <div class="text-center">
        <img src="{% static 'img/favicon.ico' %}" alt="favicon">
    </div>
    <br>

{% endblock %}